### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by amyquispe** [jaellysbales/HW_03-20#1]
General comment: I find your comments very helpful, but putting them inline with the code makes your lines very long. Would suggest placing comments on their own lines above the relevant code portions.

Divisor Pattern Art

Overall very good! Looks correct and clean.

Wanted to point out that while this does the job:

 for (j = 1; j < n; j++) {
                System.out.print(divide(i, j));
            }
 System.out.println(divide(i,j));

You could instead check j <= n and remove the print statement that's outside the loop.

Twenty Questions Game

There are a few different ways you could have structured the different cases. What you did works and is easy to follow, but it might be interesting for you to think of other ways you could have done that as well.

Small user experience suggestion: Print out what the number was if the user didn't guess it after 20 questions. They might be curious.

Fibonacci

This is correct, but it was difficult to immediately see why. The for loop is somewhat odd:

 for (int place = 1; place < n; place++) {
                nthNumber = fib1 + fib2;
                fib1 = fib2;
                fib2 = nthNumber;
            }

The "place" begins at 1 and stops when it's strictly less than n, and it's hard to see how "place" is related to the index of the fibonacci number being calculated. I'd suggest either making the code more clear or having a comment explaining this.

A Pretty Title

The API for printTitle takes in both a title and an underlying character, but yours only took in a title. The way you structured your code, it would not be that difficult to correct this, which is a good sign.

Really appreciate how you placed exceptions[] at the top of the file. All of your code is very well organized.

Verbosity Calculator

Looks good - appreciate the comment above the Mrs./Mr./Dr. exception. Makes your code easy to edit/correct for future use.

**Comment by jaellysbales** [comment]
Hi, Amy!

Thank you so much for taking the time to review my code. I really appreciate your thoughtful comments and will review and revise my code accordingly. I am still working out how to "think like a programmer" and produce efficient code, but your comments are encouraging.

All best,
Jaellys
